# Generated by Django 4.1.2 on 2022-10-31 18:49

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_comment_image_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена услуги'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_tel',
            field=phone_field.models.PhoneField(blank=True, default=0, help_text='Введите свой номер телефона в формате +375-XX-XXX-XX-XX', max_length=31, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('NS', 'Нет слов'), ('NM', 'Не мелочи'), ('SN', 'Срочно надо'), ('PV', 'Почтенный возраст'), ('PR', 'По рукам')], default='NM', max_length=2, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Содержание комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_of_creation',
            field=models.DateTimeField(verbose_name='Дата создания комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_adress',
            field=models.CharField(max_length=300, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_description',
            field=models.TextField(verbose_name='Пожелания по доставке'),
        ),
    ]
